# This is a basic workflow to help you get started with Actions

name: arm32

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run setup
        id: setup
        with:
          arch: armv7
          distro: ubuntu18.04
          ref: develop
          submodules: recursive
          path: 'taos-tools'
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Step that prints name of pull request's base branch
        run: |
          echo "The uname output was ${{ steps.setup.outputs.uname }}"
          echo "Pull request's base branch is: ${BASE_BRANCH}"
          echo "Pull request's branch is: ${GITHUB_REF##*/}"
          echo "Pull request's head ref is: ${GITHUB_HEAD_REF}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'

      - name: Checkout tdengine
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: 'develop'

      - name: Change time zone
        run: |
          echo "The uname output was ${{ steps.setup.outputs.uname }}"
          sudo timedatectl set-timezone Asia/Shanghai
          sudo date
          
      - name: Checkout TDengine with same branch of taos-tools
        run: |
          echo "The uname output was ${{ steps.setup.outputs.uname }}"
          cd TDengine
          git pull
          git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
          git submodule update --init --recursive
        if: github.event_name == 'pull_request'

      - name: Checkout TDengine's taos-tools to PR number
        if: github.event_name == 'pull_request'
        run: |
          echo "The uname output was ${{ steps.setup.outputs.uname }}"
          cd TDengine/src/kit/taos-tools
          git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
          git checkout -qf FETCH_HEAD
          
      - name: Build tdengine
        run: |
          echo "The uname output was ${{ steps.setup.outputs.uname }}"
          sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
          cd TDengine
          mkdir debug
          cd debug
          cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true
          make
          sudo make install
