name: taos-tools

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout taos-tools
        uses: actions/checkout@v2
        with:
          path: 'taos-tools'

      - name: Checkout tdengine
        uses: actions/checkout@v2
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: 'develop'

      - name: Install tdengine
        run: cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=false && make && sudo make install

      - name: Start tdengine
        run: nohup sudo taosd &

      - name: Install dependencies
        run: sudo apt install gcc build-essential libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y

      - name: Configure CMake
        run: cmake -B ./taos-tools/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ./taos-tools/build

      - name: Test
        working-directory: ./taos-tools/build
        run: ctest --verbose